packages/core/src/address/address.advanced.ts
packages/core/src/address/index.ts
packages/core/src/bytes/advanced.ts
packages/core/src/bytes/index.ts
packages/core/src/ckb/script.ts
packages/core/src/ckb/transaction.ts
packages/core/src/client/jsonRpc/index.ts
packages/core/src/fixedPoint/index.ts
packages/core/src/hasher/index.ts
packages/core/src/hex/index.ts
packages/core/src/num/index.ts
packages/core/src/signer/btc/signerBtc.ts
packages/core/src/signer/btc/signerBtcPublicKeyReadonly.ts
packages/core/src/signer/ckb/signerCkbScriptReadonly.ts
packages/core/src/signer/evm/signerEvm.ts
packages/core/src/signer/evm/signerEvmAddressReadonly.ts
packages/core/src/signer/helpers.ts
packages/core/src/signer/signer.ts

chore: ts-docs for ccc core function

---

packages/eip6963/src/eip1193.advanced.ts
packages/eip6963/src/eip6963.advanced.ts
packages/eip6963/src/signer.ts
packages/eip6963/src/signersFactory.ts
packages/joy-id/src/btc/index.ts
packages/joy-id/src/ckb/index.ts
packages/joy-id/src/common/index.ts
packages/joy-id/src/connectionsStorage/index.ts
packages/joy-id/src/evm/index.ts
packages/joy-id/src/signerFactory/index.ts
packages/lumos-patches/src/index.ts
packages/okx/src/signer.ts
packages/okx/src/signersFactory.ts
packages/uni-sat/src/advancedBarrel.ts
packages/uni-sat/src/signer.ts
packages/uni-sat/src/signersFactory.ts

update: ts-docs

---

packages/core/src/signer/ckb/index.ts
packages/core/src/signer/ckb/signerCkbPrivateKey.ts
packages/core/src/signer/signer/index.ts
packages/demo/app/home.tsx

- add sign transction by private key for ckb

feat(core): ckb private key signer

---

packages/joy-id/src/btc/index.ts

fix(joy-id): p2tr address type

---

.changeset/nasty-frogs-wonder.md
packages/ccc/src/signersController.ts
packages/connector-react/src/hooks/useCcc.tsx
packages/connector/src/scenes/connected.ts
packages/core/src/client/client.ts
packages/core/src/client/clientPublicMainnet.advanced.ts
packages/core/src/client/clientPublicTestnet.advanced.ts
packages/core/src/client/jsonRpc/index.ts
packages/core/src/client/transports/webSocket.ts
packages/demo/src/app/connected/(tools)/NervosDao/page.tsx
packages/demo/src/app/connected/(tools)/TimeLockedTransfer/page.tsx
packages/demo/src/app/connected/page.tsx
packages/xverse/src/sat-connect-core/provider.advanced.ts

feat(demo): transfer with timelock

---

packages/connector/src/components/dialog.ts

Trial submission to go through the process. Increase dialog close and back button

fix: close&back icon in connector dialog increase 25%

---

.changeset/witty-dingos-add.md
packages/core/src/ckb/transaction.ts

fix: `epochFromHex` failed if the arg is not 7 bytes

---

packages/playground/package.json
packages/playground/src/app/execute/index.ts
pnpm-lock.yaml

@ckb-ccc/core/advanced
@ckb-ccc/ccc/advanced
@ckb-ccc/spore
@ckb-ccc/spore/advanced

feat(playground): import extra packages

---

packages/demo/src/components/Dropdown.tsx

style: add overflow-y-scroll for clusters selector dropdown

---

.changeset/strong-countries-help.md
packages/rei/src/signersFactory.ts

Change the object from window.ckb to window.rei.ckb

fix: update window.rei.ckb

---

.changeset/eighty-ties-fold.md
.github/workflows/publish.yaml
packages/core/package.json
packages/joy-id/package.json
packages/lumos-patches/package.json
pnpm-lock.yaml

check security problem https://github.com/ckb-devrel/ccc/security/dependabot/32

chore: bump @joyid/ckb version

---

packages/spore/src/cluster/index.ts
packages/spore/src/spore/index.ts

Improve function parameters documentation and destructuring

refactor: improve function parameters documentation and destructuring

---

packages/playground/package.json
packages/playground/src/app/components/Editor.tsx
packages/playground/src/app/execute/index.ts
packages/playground/src/app/page.tsx
packages/playground/src/app/tabs/Console.tsx
pnpm-lock.yaml

feat(playground): tsx support

---

.changeset/chilly-years-kick.md
.changeset/new-flowers-accept.md
.changeset/twenty-pants-itch.md
packages/core/src/ckb/script.ts
packages/core/src/ckb/transaction.ts
packages/core/src/client/client.ts
packages/core/src/client/clientPublicMainnet.advanced.ts
packages/core/src/client/clientPublicMainnet.ts
packages/core/src/client/clientPublicTestnet.advanced.ts
packages/core/src/client/clientPublicTestnet.ts
packages/core/src/client/clientTypes.ts
packages/core/src/client/index.ts
packages/core/src/client/knownScript.ts
packages/core/src/signer/ckb/signerCkbPublicKey.ts
packages/demo/src/app/connected/(tools)/NervosDao/page.tsx
packages/joy-id/src/ckb/index.ts
packages/playground/src/app/components/Cell.tsx
packages/playground/src/app/tabs/Transaction.tsx

This fixes fee calculation for DAO withdrawal txs.
If devs don't change the tx composing logic, sending tx will fail.

feat(core): calculate Nervos DAO profit as input capacity

---

.changeset/cyan-melons-hang.md
packages/core/src/molecule/codec.ts

fix(core): falsy value is not empty in mol.Option

---

.changeset/olive-ears-walk.md
packages/core/src/ckb/transaction.test.ts
packages/core/src/ckb/transaction.ts

feat(core): try to avoid extra udt occupation

---

packages/core/src/client/cache/cache.ts
packages/core/src/client/cache/memory.advanced.ts
packages/core/src/client/cache/memory.ts
packages/core/src/client/client.ts
packages/core/src/client/clientTypes.advanced.ts

Make CONFIRMED_BLOCK_TIME configurable

---

.changeset/six-steaks-grab.md
packages/core/src/client/cache/memory.advanced.ts

Simplify MapLru, while improving Complexity

---

packages/core/src/ckb/script.ts
packages/core/src/ckb/transaction.ts
packages/core/src/client/client.ts

Improve performance of Script & OutPoint eq

---

packages/playground/src/app/context.tsx

fix(playground): some messages are not displyed

---

.changeset/tangy-memes-sit.md
packages/core/src/utils/index.test.ts
packages/core/src/utils/index.ts

feat(core): `reduce` and `reduceAsync` for `Iterable`

---

.changeset/ripe-camels-grin.md
packages/core/src/client/clientPublicMainnet.advanced.ts
packages/core/src/client/clientPublicTestnet.advanced.ts

chore(core): update JoyId celldeps

---

packages/demo/src/app/connected/page.tsx
packages/demo/src/app/utils/(tools)/DepGroup/page.tsx
packages/demo/src/app/utils/page.tsx
packages/demo/src/components/Message.tsx

feat(demo): dep group management

---

packages/udt/src/udt/index.ts

fix(core): udt mint outputData length not eq 16
